// <auto-generated />
using Layer.Architecture.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Layer.Architecture.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220928132916_Final")]
    partial class Final
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Layer.Architecture.Domain.Models.Entrevistado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<int>("VagaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VagaId");

                    b.ToTable("Entrevistados");
                });

            modelBuilder.Entity("Layer.Architecture.Domain.Models.EntrevistadoNNTecnologias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EntrevistadoId")
                        .HasColumnType("int");

                    b.Property<int>("TecId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntrevistadoId");

                    b.HasIndex("TecId");

                    b.ToTable("entrevistadoNNTecnologias");
                });

            modelBuilder.Entity("Layer.Architecture.Domain.Models.Tecnologias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tecnologias");
                });

            modelBuilder.Entity("Layer.Architecture.Domain.Models.Vaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int>("Salario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("vagas");
                });

            modelBuilder.Entity("Layer.Architecture.Domain.Models.VagaNNTecnologias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<int>("TecId")
                        .HasColumnType("int");

                    b.Property<int>("VagaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TecId");

                    b.HasIndex("VagaId");

                    b.ToTable("vagaNNTecnologias");
                });

            modelBuilder.Entity("Layer.Architecture.Domain.Models.Entrevistado", b =>
                {
                    b.HasOne("Layer.Architecture.Domain.Models.Vaga", "Vaga")
                        .WithMany("Entrevistados")
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("Layer.Architecture.Domain.Models.EntrevistadoNNTecnologias", b =>
                {
                    b.HasOne("Layer.Architecture.Domain.Models.Entrevistado", "Entrevistado")
                        .WithMany("Tecnologias")
                        .HasForeignKey("EntrevistadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Layer.Architecture.Domain.Models.Tecnologias", "Tecnologias")
                        .WithMany("entrevistados")
                        .HasForeignKey("TecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrevistado");

                    b.Navigation("Tecnologias");
                });

            modelBuilder.Entity("Layer.Architecture.Domain.Models.VagaNNTecnologias", b =>
                {
                    b.HasOne("Layer.Architecture.Domain.Models.Tecnologias", "Tecnologias")
                        .WithMany("vagas")
                        .HasForeignKey("TecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Layer.Architecture.Domain.Models.Vaga", "Vaga")
                        .WithMany("Tecnologias")
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tecnologias");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("Layer.Architecture.Domain.Models.Entrevistado", b =>
                {
                    b.Navigation("Tecnologias");
                });

            modelBuilder.Entity("Layer.Architecture.Domain.Models.Tecnologias", b =>
                {
                    b.Navigation("entrevistados");

                    b.Navigation("vagas");
                });

            modelBuilder.Entity("Layer.Architecture.Domain.Models.Vaga", b =>
                {
                    b.Navigation("Entrevistados");

                    b.Navigation("Tecnologias");
                });
#pragma warning restore 612, 618
        }
    }
}
